version: 0.2

phases:
  install:
    runtime-versions: 
      python: 3.12
  build:
    commands:
    - echo "Zipping the lambda function"
    - zip -r lambda.zip lambda
  artifacts:
    files:
    - lambda_function.zip
