AWSTemplateFormatVersion: '2010-09-09'
Description: 'CFT for creating lambda function'

Resources:
    LambdaExecutionRole:
        Type: AWS::IAM::Role
        Properties:
          RoleName: !Sub "${AWS::StackName}-LambdaFunctionRole"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Principal:
                  Service: 
                  - "lambda.amazonaws.com" 
                Action: "sts:AssumeRole"
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AdministratorAccess
    
    AdminLambdaFunction:
        Type: AWS::Lambda::Function
        Properties:
          FunctionName: test-lambda
          Runtime: python3.12
          Handler: lambda_function.lambda_handler
          Role: !GetAtt LambdaExecutionRole.Arn
          Code:
            S3Bucket: suryansh-jark-bucket
            S3Key: lambda-test/lambda_function.zip
          Timeout: 900
